include: [../defaults.yaml, ../model/yolov5s.yaml]
task:
  label: random-replay
  parent_result: null
data:
  layout: ../data/self_improving.yaml
  current: [stage0]
  candidate: [stage0]
  validation: [val]
  test: [test]
initialization: {source: parent, checkpoint: last}
select_policy:
  name: random_replay
  params: {replay_size: 500}
