include: ../../../../../configs/sequence/_base_learning_curve_full_cold.yaml
sequence: {name: Balance_Learning_Curve_random_s43, output_root: ../../experiment/sequence}
data:
  layout: ../data/balance_2batch_random_s43.yaml
